//message
export const RESET_AUTH_MESSAGE_SUCCESS = "RESET_AUTH_MESSAGE_SUCCESS";
export const RESET_USER_MESSAGE_SUCCESS = "RESET_USER_MESSAGE_SUCCESS";

//home
export const GET_HOME_DATA = "GET_HOME_DATA";
export const GET_HOME_DATA_SUCCESS = "GET_HOME_DATA_SUCCESS";
export const GET_HOME_DATA_FAILED = "GET_HOME_DATA_FAILED";

//auth
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const RESEND_ACTIVATION_EMAIL_SUCCESS =
  "RESEND_ACTIVATION_EMAIL_SUCCESS";
export const VALIDATE_EMAIL_SUCCESS = "VALIDATE_EMAIL_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const SEND_RESET_PASSWORD_SUCCESS = "SEND_RESET_PASSWORD_SUCCESS";
export const SEND_VERIFICATION_CODE_SUCCESS = "SEND_VERIFICATION_CODE_SUCCESS";
export const SEND_CHANGE_EMAIL_SUCCESS = "SEND_CHANGE_EMAIL_SUCCESS";
export const CHECK_VERIFICATION_CODE_SUCCESS =
  "CHECK_VERIFICATION_CODE_SUCCESS";
export const STORE_USER_EMAIL_SUCCESS = "STORE_USER_EMAIL_SUCCESS";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const UNAUTH_USER_SUCCESS = "UNAUTH_USER_SUCCESS";

//user
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const UPDATE_USER_INFO_SUCCESS = "UPDATE_USER_INFO_SUCCESS";
export const GET_USER_ADDRESS_SUCCESS = "GET_USER_ADDRESS_SUCCESS";
export const POST_USER_ADDRESS_SUCCESS = "POST_USER_ADDRESS_SUCCESS";
export const DEFAULT_USER_ADDRESS_SUCCESS = "DEFAULT_USER_ADDRESS_SUCCESS";
export const DELETE_USER_ADDRESS_SUCCESS = "DELETE_USER_ADDRESS_SUCCESS";
export const SAVE_USER_ADDRESS_SUCCESS = "SAVE_USER_ADDRESS_SUCCESS";
export const CHANGE_USER_ADDRESS_SUCCESS = "CHANGE_USER_ADDRESS_SUCCESS";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_BY_TYPE = "GET_POST_BY_TYPE";
export const GET_USER_INFO_START = "GET_USER_INFO_START";
export const GET_USER_REVIEW_SUCCESS = "GET_USER_REVIEW_SUCCESS";

//moment
export const REQUEST_ALL_MOMENTS = "REQUEST_ALL_MOMENTS";
export const REQUEST_ALL_MOMENTS_SUCCESS = "REQUEST_ALL_MOMENTS_SUCCESS";
export const REQUEST_ALL_MOMENTS_FAILD = "REQUEST_ALL_MOMENTS_FAILD";
export const REQUEST_MORE_MOMENTS = "REQUEST_MORE_MOMENTS";
export const REQUEST_MORE_MOMENTS_SUCCESS = "REQUEST_MORE_MOMENTS_SUCCESS";
export const REQUEST_MORE_MOMENTS_FAILED = "REQUEST_MORE_MOMENTS_FAILED";
export const GET_MOMENT_DETAIL = "GET_MOMENT_DETAIL";

//service
export const GET_SERVICE_CATEGORY_SUCCESS = "GET_SERVICE_CATEGORY_SUCCESS";
export const GET_SERVICE_SUB_CATEGORY_SUCCESS =
  "GET_SERVICE_SUB_CATEGORY_SUCCESS";
export const GET_SERVICE_LIST_SUCCESS = "GET_SERVICE_LIST_SUCCESS";
export const GET_ADDITIONAL_SERVICE_SUCCESS = "GET_ADDITIONAL_SERVICE_SUCCESS";
export const GET_SERVICE_DETAIL_SUCCESS = "GET_SERVICE_DETAIL_SUCCESS";
export const ADD_SERVICE_DETAIL_SUCCESS = "ADD_SERVICE_DETAIL_SUCCESS";
export const GET_SERVICE_PRICE_SUCCESS = "GET_SERVICE_PRICE_SUCCESS";
export const GET_SERVICE_LOCATION_LIST = "GET_SERVICE_LOCATION_LIST";
export const GET_SERVICE_REVIEW_LIST = "GET_SERVICE_REVIEW_LIST";
export const GET_SERVICE_REVIEW_LIST_START = "GET_SERVICE_REVIEW_LIST_START";
export const GET_SERVICE_DATE_LIST = "GET_SERVICE_DATE_LIST";
export const GET_PET_LIST = "GET_PET_LIST";
export const GET_SERVICE_FACILITY_SUCCESS = "GET_SERVICE_FACILITY_SUCCESS";
export const GET_DRAFT_SERVICE_LIST = "GET_DRAFT_SERVICE_LIST";
export const GET_SERVICE_ORDER_LIST = "GET_SERVICE_ORDER_LIST";
export const GET_SAVED_SERVICE = "GET_SAVED_SERVICE";
export const GET_SERVICE_ORDER_LIST_START = "GET_SERVICE_ORDER_LIST_START";
export const GET_SERVICE_DATE_LIST_START = "GET_SERVICE_DATE_LIST_START";
// export const ADD_PET_SUCCESS = "ADD_PET_SUCCESS";

//product
export const GET_PRODUCT_CATEGORY_SUCCESS = "GET_PRODUCT_CATEGORY_SUCCESS";
export const GET_PRODUCT_SUB_CATEGORY_SUCCESS =
  "GET_PRODUCT_SUB_CATEGORY_SUCCESS";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS";
export const GET_ITEM_PET_CATEGORY = "GET_ITEM_PET_CATEGORY";
export const GET_ITEM_PET_SUBCATEGORY = "GET_ITEM_PET_SUBCATEGORY";
export const GET_SIMILAR_PRODUCT_LIST = "GET_SIMILAR_PRODUCT_LIST";
export const GET_ITEM_REVIEW = "GET_ITEM_REVIEW";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_ITEM_ORDER = "GET_ITEM_ORDER";
export const GET_SAVED_ITEM = "GET_SAVED_ITEM";
export const GET_PRODUCT_DETAIL_START = "GET_PRODUCT_DETAIL_START";

//chat
export const GET_USER_CONTACT_LIST_SUCCESS = "GET_USER_CONTACT_LIST_SUCCESS";
export const UPDATE_USER_CONTACT_LIST_SUCCESS =
  "UPDATE_USER_CONTACT_LIST_SUCCESS";

//setting
export const SHOW_AUTH_MODAL_SUCCESS = "SHOW_AUTH_MODAL_SUCCESS";
export const HIDE_AUTH_MODAL_SUCCESS = "HIDE_AUTH_MODAL_SUCCESS";

//notification 
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const READ_NOTIFICATION_SUCCESS = "READ_NOTIFICATION_SUCCESS";